# Maximum line length
line-length = 120

[lint]
extend-select = [
    "E501",
    "UP",   # pyupgrade (auto upgrade syntax for newer versions of python)
    "D"     # pydocstyle (check docstrings)
]
ignore = [
    "D100" # Ignore missing top-leveldocstrings for public modules
]

[lint.pydocstyle]
convention = "google"
