name: Build and Deploy to Production

on:
  push:
    tags:
      - "v*"
    branches:
      - main

jobs:
  prep-production-server:
    name: Prep production server
    runs-on: ubuntu-latest
    env:
      SSH_BASE: >-
        ssh
        -o UserKnownHostsFile=${{ github.workspace }}/production-srv-signature
        -o StrictHostKeyChecking=yes
        -i ${{ github.workspace }}/ci-cd-key
        ${{ secrets.PROD_SRV_USER }}@${{ secrets.PROD_SRV_HOST }}
    steps:
      - name: Copy production server key
        run: |
          echo "${{ secrets.CI_CD_SSH_KEY }}" > ${{ github.workspace }}/ci-cd-key
          chmod 600 ${{ github.workspace }}/ci-cd-key

      - name: Copy production server signature
        run: |
          echo "${{ secrets.PROD_SRV_SIGNATURE }}" > ${{ github.workspace }}/production-srv-signature
          chmod 600 ${{ github.workspace }}/production-srv-signature

      - name: Stop old production server container
        # This is stopped and not removed to minimize downtime
        run: |
          ${{ env.SSH_BASE }} '
            docker stop personal-website || true'

      - name: Make a copy of old production data
        run: |
          ${{ env.SSH_BASE }} '
            sudo rm -rf ${{ vars.PROD_DATA_PATH }}.backup
            sudo cp ${{ vars.PROD_DATA_PATH }} ${{ vars.PROD_DATA_PATH }}.backup'

      - name: Restart production server container
        run: |
          ${{ env.SSH_BASE }} '
            docker start personal-website'

  build-and-push-production-docker-image:
    name: Build and push the production docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ gitea.server_url }}
          username: ${{ secrets.GCR_USERNAME }}
          password: ${{ secrets.GCR_ACCESS_TOKEN }}

      - name: Build and push the production docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.INSTANCE_HOST }}/${{ secrets.GCR_USERNAME }}/personal-website:production
          cache-from: type=local,src=${{ github.workspace }}/buildkit
          cache-to: type=local,dest=${{ github.workspace }}/buildkit,mode=max
